[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "seamless_pdf"
version = "0.1.0"
authors = [
  { name="AnthonyPC", email="anthony@example.com" },
]
description = "A tool to convert HTML documents to continuous PDFs"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "playwright",
]

[tool.setuptools.packages.find]
where = ["src"]
